@backend_HostAddress = http://localhost:5056


###
POST {{backend_HostAddress}}/user/login
Content-Type: application/json

{
    "email": "MamthaUchil@gmail.com",
    "password": "mamtha"
}    

###
POST {{backend_HostAddress}}/user/signup
Content-Type: application/json

{
    "name":"neha2",
    "email":"neha2@gmail.com",
    "password":"Neha@123",
    "phone":"8806572477"
}

###
GET {{backend_HostAddress}}/appointment?userId=25



###
GET {{backend_HostAddress}}/appointment/dashboard
###
POST {{backend_HostAddress}}/appointment/book
Content-Type: application/json

{
    "userId": 25,
    "appointmentDate": "2026-02-12",
    "appointmentTime": "15:30:00",
    "service": "facial",
    "additionalNotes": "gold",
    "status":false
}



###
DELETE {{backend_HostAddress}}/appointment?appointmentId=25

###
PUT {{backend_HostAddress}}/user/update
Content-Type: application/json

{
    "id":26,
    "name":"MamthaUchil",
    "email":"MamthaUchil@gmail.com",
    "phone":"8793963870"
}

###
PUT {{backend_HostAddress}}/appointment/update
Content-Type: application/json

{
    "appointmentId":100,
    "status":true
   
}